# -*- coding: utf-8 -*-
"""Hand and Point System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZmPJdGTuz5GMtvM_qYRe7gOWzf7hiTm
"""

import random

# Letter distribution and points (simplified)
LETTER_POOL = {
    "A": 9, "B": 2, "C": 2, "D": 4, "E": 12, "F": 2, "G": 3,
    "H": 2, "I": 9, "J": 1, "K": 1, "L": 4, "M": 2, "N": 6,
    "O": 8, "P": 2, "Q": 1, "R": 6, "S": 4, "T": 6, "U": 4,
    "V": 2, "W": 2, "X": 1, "Y": 2, "Z": 1
}

LETTER_SCORES = {
    "A": 1, "B": 3, "C": 3, "D": 2, "E": 1, "F": 4, "G": 2,
    "H": 4, "I": 1, "J": 8, "K": 5, "L": 1, "M": 3, "N": 1,
    "O": 1, "P": 3, "Q": 10, "R": 1, "S": 1, "T": 1, "U": 1,
    "V": 4, "W": 4, "X": 8, "Y": 4, "Z": 10
}

# --- Helper functions ---
def draw_letters(num=7):
    """Draw random letters from the pool."""
    letters = []
    available_letters = [letter for letter, count in LETTER_POOL.items() for _ in range(count)]
    for _ in range(num):
        if available_letters:
            letters.append(random.choice(available_letters))
    return letters

def score_word(word):
    """Calculate score for a given word."""
    return sum(LETTER_SCORES.get(letter.upper(), 0) for letter in word)

def can_form_word(word, hand):
    """Check if the player can form the word with their letters."""
    temp_hand = hand.copy()
    for letter in word.upper():
        if letter in temp_hand:
            temp_hand.remove(letter)
        else:
            return False
    return True

def replace_used_letters(hand, word):
    """Replace letters used in the word with new ones."""
    for letter in word.upper():
        if letter in hand:
            hand.remove(letter)
    new_letters = draw_letters(len(word))
    hand.extend(new_letters)
    return hand

# --- Main game ---
def scrabble_game():
    players = ["Player 1", "Player 2"]
    hands = {player: draw_letters() for player in players}
    scores = {player: 0 for player in players}

    print("🎲 Welcome to Mini Scrabble!")
    print("----------------------------")

    for round_num in range(5):  # play 5 rounds for demo
        print(f"\n--- Round {round_num + 1} ---")
        for player in players:
            print(f"\n{player}'s turn")
            print(f"Letters: {' '.join(hands[player])}")
            print(f"Current Score: {scores[player]}")

            word = input("Enter a word (or press Enter to skip): ").strip().upper()
            if not word:
                print(f"{player} skips this turn.")
                continue

            if can_form_word(word, hands[player]):
                word_score = score_word(word)
                scores[player] += word_score
                print(f"✅ '{word}' is valid! You earned {word_score} points.")
                hands[player] = replace_used_letters(hands[player], word)
            else:
                print(f"❌ You can't form '{word}' with your letters!")

            print(f"New Hand: {' '.join(hands[player])}")
            print(f"Total Score: {scores[player]}")

    print("\n🏁 Final Scores:")
    for player, score in scores.items():
        print(f"{player}: {score} points")

    winner = max(scores, key=scores.get)
    print(f"\n🎉 {winner} wins the game! 🎉")

# Run the game
if __name__ == "__main__":
    scrabble_game()